### ISSUE TITLE
Input field background color is overridden

### ISSUE THREAD

**Issue by gribelu** [chemerisuk/better-form-validation#4]
Hello,

The script sets the following style:

`DOM.importStyles("input[aria-invalid]", "background:none no-repeat right center / auto 100% content-box");`

If the input field has an initial `background-color` value it will become transparent when validation kicks in. You should probably set the individual background properties such as `background-repeat` etc.

Cheers!

**Comment by gribelu** [comment]
I ended up modifying the plugin. I used the following:

`DOM.importStyles("input[aria-invalid]", "background-size: auto 1.4em; background-repeat: no-repeat; background-position: right center; background-origin: content-box;");`

That works for now but I think that ideally the CSS should be moved to a `.css` file.

Thanks.

**Comment by chemerisuk** [comment]
Thanks @gribelu . Sorry missed your comments. I'll review that css in the release version.

**Comment by Jaybuz** [comment]
Using a CSS file instead would be great as I've found it overrides Chromes built in autofill styling.

Are you still developing this script?

**Comment by chemerisuk** [comment]
@Jaybuz from time to time, frankly speaking... I'll probably update the plugin for better-dom 3 but I can't give you any time estimates.

**Comment by chemerisuk** [comment]
@Jaybuz checkout 1.5.0 where bundled styles do not touch input bakcground
